# Generated by Django 4.0.4 on 2022-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('phone', models.CharField(max_length=30, verbose_name='شماره تلفن')),
                ('message', models.TextField(blank=True, verbose_name='متن پیام')),
                ('listing', models.CharField(max_length=200, verbose_name='عنوان آگهی')),
                ('listing_id', models.IntegerField(verbose_name='شناسه آگهی')),
                ('user_id', models.IntegerField(blank=True, verbose_name='شناسه کاربر')),
                ('contact_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تماس')),
            ],
        ),
    ]
