# Generated by Django 4.0.4 on 2022-08-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس\u200cها', 'verbose_name_plural': 'تماس\u200cها'},
        ),
    ]
