# Generated by Django 4.0.4 on 2022-08-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='تعداد حمام و دستشویی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=50, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='descriptions',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(default=0, verbose_name='تعداد پارکینگ'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='اندازه زمین'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='تصویر ۱'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='تصویر ۲'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='تصویر ۳'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='تصویر ۴'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='تصویر ۵'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='تصویر ۶'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default='On Agreement', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtors.realtor', verbose_name='مشاور املاک'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='square_meters',
            field=models.IntegerField(verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(max_length=50, verbose_name='کدپستی'),
        ),
    ]
