# Generated by Django 4.0.4 on 2022-08-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_address_alter_listing_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'لیست شده\u200cها', 'verbose_name_plural': 'لیست شده\u200cها'},
        ),
    ]
