# Generated by Django 4.0.4 on 2022-08-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_descriptions_alter_realtor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'مشاورین املاک', 'verbose_name_plural': 'مشاورین املاک'},
        ),
    ]
